package com.dreamevents.backend.service;

import com.dreamevents.backend.entity.Booking;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class EmailService {

    @Autowired
    private JavaMailSender mailSender;

    @Value("${app.mail.owner-email:owner@dreamevents.com}")
    private String ownerEmail;

    @Value("${spring.mail.username:}")
    private String senderEmail;

    public void sendBookingNotification(Booking booking) {
        String from = (senderEmail != null && !senderEmail.trim().isEmpty()) ? senderEmail : "noreply@dreamevents.com";
        
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(from);
            helper.setTo(ownerEmail);
            helper.setSubject("New Booking Request Submitted - " + booking.getClientName());

            String htmlContent = buildHtmlContent(booking);
            helper.setText(htmlContent, true);

            mailSender.send(message);
            log.info("Successfully sent booking request email alert to owner at: {}", ownerEmail);
        } catch (Exception e) {
            log.error("Failed to send booking notification email to owner: {}. Booking ID: {}", e.getMessage(), booking.getId());
        }
    }

    private String buildHtmlContent(Booking booking) {
        String attachmentLink = (booking.getAttachmentUrl() != null && !booking.getAttachmentUrl().isEmpty()) 
                ? String.format("<p><strong>Attachment</strong>: <a href=\"%s\" target=\"_blank\">View Uploaded Document/Image</a></p>", booking.getAttachmentUrl())
                : "<p><strong>Attachment</strong>: None</p>";

        return "<html>" +
                "<body style=\"font-family: Arial, sans-serif; color: #333; line-height: 1.6;\">" +
                "<div style=\"max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; padding: 24px; border-radius: 12px;\">" +
                "<h2 style=\"color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;\">New Booking Request</h2>" +
                "<p>A customer has submitted a new event booking inquiry on <strong>Dream Events</strong>.</p>" +
                "<h3>Customer Details</h3>" +
                "<p><strong>Name</strong>: " + booking.getClientName() + "</p>" +
                "<p><strong>Email</strong>: " + booking.getEmail() + "</p>" +
                "<p><strong>Phone</strong>: " + booking.getPhone() + "</p>" +
                "<h3>Event Specifications</h3>" +
                "<p><strong>Selected Package</strong>: " + booking.getEventPackage().getName() + " (" + booking.getEventPackage().getTier() + ")</p>" +
                "<p><strong>Event Date</strong>: " + booking.getEventDate().toString() + "</p>" +
                "<p><strong>Guest Count</strong>: " + booking.getGuestCount() + " guests</p>" +
                "<p><strong>Location</strong>: " + booking.getLocation() + "</p>" +
                "<p><strong>Notes/Remarks</strong>: " + (booking.getCustomNotes() != null ? booking.getCustomNotes() : "N/A") + "</p>" +
                attachmentLink +
                "<br>" +
                "<div style=\"text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; color: #718096;\">" +
                "<p>This email was auto-generated by the Dream Events Booking Platform.</p>" +
                "</div>" +
                "</div>" +
                "</body>" +
                "</html>";
    }
}
